create_clock -period 10.000 -name usb_clk -waveform {0.000 5.000} [get_ports usb_clk]
create_clock -period 5.000 -name usb_clk -waveform {0.000 2.500} [get_ports sys_clk_p]



connect_debug_port u_ila_0/probe4 [get_nets [list {mem_top_inst/genblk1[1].sram_top_inst/addrb_r[0]} {mem_top_inst/genblk1[1].sram_top_inst/addrb_r[1]} {mem_top_inst/genblk1[1].sram_top_inst/addrb_r[2]} {mem_top_inst/genblk1[1].sram_top_inst/addrb_r[3]} {mem_top_inst/genblk1[1].sram_top_inst/addrb_r[4]} {mem_top_inst/genblk1[1].sram_top_inst/addrb_r[5]} {mem_top_inst/genblk1[1].sram_top_inst/addrb_r[6]} {mem_top_inst/genblk1[1].sram_top_inst/addrb_r[7]} {mem_top_inst/genblk1[1].sram_top_inst/addrb_r[8]} {mem_top_inst/genblk1[1].sram_top_inst/addrb_r[9]} {mem_top_inst/genblk1[1].sram_top_inst/addrb_r[10]} {mem_top_inst/genblk1[1].sram_top_inst/addrb_r[11]} {mem_top_inst/genblk1[1].sram_top_inst/addrb_r[12]} {mem_top_inst/genblk1[1].sram_top_inst/addrb_r[13]} {mem_top_inst/genblk1[1].sram_top_inst/addrb_r[14]} {mem_top_inst/genblk1[1].sram_top_inst/addrb_r[15]}]]
connect_debug_port u_ila_0/probe24 [get_nets [list {mem_top_inst/genblk1[1].sram_top_inst/enb_r}]]


connect_debug_port u_ila_0/probe0 [get_nets [list {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[0]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[1]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[2]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[3]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[4]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[5]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[6]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[7]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[8]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[9]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[10]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[11]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[12]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[13]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[14]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[15]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[16]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[17]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[18]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[19]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[20]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[21]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[22]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[23]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[24]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[25]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[26]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[27]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[28]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[29]} {receive_top_inst/genblk6[1].T0_time_inst/delta_coarse_data02_out[30]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[0]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[1]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[2]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[3]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[4]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[5]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[6]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[7]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[8]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[9]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[10]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[11]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[12]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[13]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[14]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[15]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[16]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[17]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[18]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[19]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[20]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[21]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[22]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[23]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[24]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[25]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[26]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[27]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[28]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[29]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[30]} {receive_top_inst/genblk6[1].T0_time_inst/delta_fine_data00_out[31]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[0]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[1]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[2]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[3]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[4]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[5]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[6]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[7]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[8]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[9]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[10]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[11]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[12]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[13]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[14]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[15]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[16]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[17]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[18]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[19]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[20]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[21]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[22]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[23]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[24]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[25]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[26]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[27]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[28]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[29]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[30]} {receive_top_inst/genblk6[1].T0_time_inst/p_1_in[31]}]]

connect_debug_port u_ila_0/probe3 [get_nets [list {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[0]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[1]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[2]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[3]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[4]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[5]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[6]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[7]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[8]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[9]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[10]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[11]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[12]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[13]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[14]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[15]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[16]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[17]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[18]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[19]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[20]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[21]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[22]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[23]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[24]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[25]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[26]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[27]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[28]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[29]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[30]} {receive_top_inst/genblk6[1].T0_time_inst/p_0_in[31]}]]

connect_debug_port u_ila_0/probe4 [get_nets [list {receive_top_inst/coarse_time[0]_4[0]} {receive_top_inst/coarse_time[0]_4[1]} {receive_top_inst/coarse_time[0]_4[2]} {receive_top_inst/coarse_time[0]_4[3]} {receive_top_inst/coarse_time[0]_4[4]} {receive_top_inst/coarse_time[0]_4[5]} {receive_top_inst/coarse_time[0]_4[6]} {receive_top_inst/coarse_time[0]_4[7]} {receive_top_inst/coarse_time[0]_4[8]} {receive_top_inst/coarse_time[0]_4[9]} {receive_top_inst/coarse_time[0]_4[10]} {receive_top_inst/coarse_time[0]_4[11]} {receive_top_inst/coarse_time[0]_4[12]} {receive_top_inst/coarse_time[0]_4[13]} {receive_top_inst/coarse_time[0]_4[14]} {receive_top_inst/coarse_time[0]_4[15]} {receive_top_inst/coarse_time[0]_4[16]} {receive_top_inst/coarse_time[0]_4[17]} {receive_top_inst/coarse_time[0]_4[18]} {receive_top_inst/coarse_time[0]_4[19]} {receive_top_inst/coarse_time[0]_4[20]} {receive_top_inst/coarse_time[0]_4[21]} {receive_top_inst/coarse_time[0]_4[22]} {receive_top_inst/coarse_time[0]_4[23]} {receive_top_inst/coarse_time[0]_4[24]} {receive_top_inst/coarse_time[0]_4[25]} {receive_top_inst/coarse_time[0]_4[26]} {receive_top_inst/coarse_time[0]_4[27]} {receive_top_inst/coarse_time[0]_4[28]} {receive_top_inst/coarse_time[0]_4[29]} {receive_top_inst/coarse_time[0]_4[30]} {receive_top_inst/coarse_time[0]_4[31]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {receive_top_inst/coarse_time[1]_0[0]} {receive_top_inst/coarse_time[1]_0[1]} {receive_top_inst/coarse_time[1]_0[2]} {receive_top_inst/coarse_time[1]_0[3]} {receive_top_inst/coarse_time[1]_0[4]} {receive_top_inst/coarse_time[1]_0[5]} {receive_top_inst/coarse_time[1]_0[6]} {receive_top_inst/coarse_time[1]_0[7]} {receive_top_inst/coarse_time[1]_0[8]} {receive_top_inst/coarse_time[1]_0[9]} {receive_top_inst/coarse_time[1]_0[10]} {receive_top_inst/coarse_time[1]_0[11]} {receive_top_inst/coarse_time[1]_0[12]} {receive_top_inst/coarse_time[1]_0[13]} {receive_top_inst/coarse_time[1]_0[14]} {receive_top_inst/coarse_time[1]_0[15]} {receive_top_inst/coarse_time[1]_0[16]} {receive_top_inst/coarse_time[1]_0[17]} {receive_top_inst/coarse_time[1]_0[18]} {receive_top_inst/coarse_time[1]_0[19]} {receive_top_inst/coarse_time[1]_0[20]} {receive_top_inst/coarse_time[1]_0[21]} {receive_top_inst/coarse_time[1]_0[22]} {receive_top_inst/coarse_time[1]_0[23]} {receive_top_inst/coarse_time[1]_0[24]} {receive_top_inst/coarse_time[1]_0[25]} {receive_top_inst/coarse_time[1]_0[26]} {receive_top_inst/coarse_time[1]_0[27]} {receive_top_inst/coarse_time[1]_0[28]} {receive_top_inst/coarse_time[1]_0[29]} {receive_top_inst/coarse_time[1]_0[30]} {receive_top_inst/coarse_time[1]_0[31]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {receive_top_inst/stop_coarse_data[1]_1[0]} {receive_top_inst/stop_coarse_data[1]_1[1]} {receive_top_inst/stop_coarse_data[1]_1[2]} {receive_top_inst/stop_coarse_data[1]_1[3]} {receive_top_inst/stop_coarse_data[1]_1[4]} {receive_top_inst/stop_coarse_data[1]_1[5]} {receive_top_inst/stop_coarse_data[1]_1[6]} {receive_top_inst/stop_coarse_data[1]_1[7]} {receive_top_inst/stop_coarse_data[1]_1[8]} {receive_top_inst/stop_coarse_data[1]_1[9]} {receive_top_inst/stop_coarse_data[1]_1[10]} {receive_top_inst/stop_coarse_data[1]_1[11]} {receive_top_inst/stop_coarse_data[1]_1[12]} {receive_top_inst/stop_coarse_data[1]_1[13]} {receive_top_inst/stop_coarse_data[1]_1[14]} {receive_top_inst/stop_coarse_data[1]_1[15]} {receive_top_inst/stop_coarse_data[1]_1[16]} {receive_top_inst/stop_coarse_data[1]_1[17]} {receive_top_inst/stop_coarse_data[1]_1[18]} {receive_top_inst/stop_coarse_data[1]_1[19]} {receive_top_inst/stop_coarse_data[1]_1[20]} {receive_top_inst/stop_coarse_data[1]_1[21]} {receive_top_inst/stop_coarse_data[1]_1[22]} {receive_top_inst/stop_coarse_data[1]_1[23]} {receive_top_inst/stop_coarse_data[1]_1[24]} {receive_top_inst/stop_coarse_data[1]_1[25]} {receive_top_inst/stop_coarse_data[1]_1[26]} {receive_top_inst/stop_coarse_data[1]_1[27]} {receive_top_inst/stop_coarse_data[1]_1[28]} {receive_top_inst/stop_coarse_data[1]_1[29]} {receive_top_inst/stop_coarse_data[1]_1[30]} {receive_top_inst/stop_coarse_data[1]_1[31]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {receive_top_inst/fine_time[0]_5[0]} {receive_top_inst/fine_time[0]_5[1]} {receive_top_inst/fine_time[0]_5[2]} {receive_top_inst/fine_time[0]_5[3]} {receive_top_inst/fine_time[0]_5[4]} {receive_top_inst/fine_time[0]_5[5]} {receive_top_inst/fine_time[0]_5[6]} {receive_top_inst/fine_time[0]_5[7]} {receive_top_inst/fine_time[0]_5[8]} {receive_top_inst/fine_time[0]_5[9]} {receive_top_inst/fine_time[0]_5[10]} {receive_top_inst/fine_time[0]_5[11]} {receive_top_inst/fine_time[0]_5[12]} {receive_top_inst/fine_time[0]_5[13]} {receive_top_inst/fine_time[0]_5[14]} {receive_top_inst/fine_time[0]_5[15]} {receive_top_inst/fine_time[0]_5[16]} {receive_top_inst/fine_time[0]_5[17]} {receive_top_inst/fine_time[0]_5[18]} {receive_top_inst/fine_time[0]_5[19]} {receive_top_inst/fine_time[0]_5[20]} {receive_top_inst/fine_time[0]_5[21]} {receive_top_inst/fine_time[0]_5[22]} {receive_top_inst/fine_time[0]_5[23]} {receive_top_inst/fine_time[0]_5[24]} {receive_top_inst/fine_time[0]_5[25]} {receive_top_inst/fine_time[0]_5[26]} {receive_top_inst/fine_time[0]_5[27]} {receive_top_inst/fine_time[0]_5[28]} {receive_top_inst/fine_time[0]_5[29]} {receive_top_inst/fine_time[0]_5[30]} {receive_top_inst/fine_time[0]_5[31]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {receive_top_inst/fine_time[1]_2[0]} {receive_top_inst/fine_time[1]_2[1]} {receive_top_inst/fine_time[1]_2[2]} {receive_top_inst/fine_time[1]_2[3]} {receive_top_inst/fine_time[1]_2[4]} {receive_top_inst/fine_time[1]_2[5]} {receive_top_inst/fine_time[1]_2[6]} {receive_top_inst/fine_time[1]_2[7]} {receive_top_inst/fine_time[1]_2[8]} {receive_top_inst/fine_time[1]_2[9]} {receive_top_inst/fine_time[1]_2[10]} {receive_top_inst/fine_time[1]_2[11]} {receive_top_inst/fine_time[1]_2[12]} {receive_top_inst/fine_time[1]_2[13]} {receive_top_inst/fine_time[1]_2[14]} {receive_top_inst/fine_time[1]_2[15]} {receive_top_inst/fine_time[1]_2[16]} {receive_top_inst/fine_time[1]_2[17]} {receive_top_inst/fine_time[1]_2[18]} {receive_top_inst/fine_time[1]_2[19]} {receive_top_inst/fine_time[1]_2[20]} {receive_top_inst/fine_time[1]_2[21]} {receive_top_inst/fine_time[1]_2[22]} {receive_top_inst/fine_time[1]_2[23]} {receive_top_inst/fine_time[1]_2[24]} {receive_top_inst/fine_time[1]_2[25]} {receive_top_inst/fine_time[1]_2[26]} {receive_top_inst/fine_time[1]_2[27]} {receive_top_inst/fine_time[1]_2[28]} {receive_top_inst/fine_time[1]_2[29]} {receive_top_inst/fine_time[1]_2[30]} {receive_top_inst/fine_time[1]_2[31]}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {receive_top_inst/stop_fine_data[1]_3[0]} {receive_top_inst/stop_fine_data[1]_3[1]} {receive_top_inst/stop_fine_data[1]_3[2]} {receive_top_inst/stop_fine_data[1]_3[3]} {receive_top_inst/stop_fine_data[1]_3[4]} {receive_top_inst/stop_fine_data[1]_3[5]} {receive_top_inst/stop_fine_data[1]_3[6]} {receive_top_inst/stop_fine_data[1]_3[7]} {receive_top_inst/stop_fine_data[1]_3[8]} {receive_top_inst/stop_fine_data[1]_3[9]} {receive_top_inst/stop_fine_data[1]_3[10]} {receive_top_inst/stop_fine_data[1]_3[11]} {receive_top_inst/stop_fine_data[1]_3[12]} {receive_top_inst/stop_fine_data[1]_3[13]} {receive_top_inst/stop_fine_data[1]_3[14]} {receive_top_inst/stop_fine_data[1]_3[15]} {receive_top_inst/stop_fine_data[1]_3[16]} {receive_top_inst/stop_fine_data[1]_3[17]} {receive_top_inst/stop_fine_data[1]_3[18]} {receive_top_inst/stop_fine_data[1]_3[19]} {receive_top_inst/stop_fine_data[1]_3[20]} {receive_top_inst/stop_fine_data[1]_3[21]} {receive_top_inst/stop_fine_data[1]_3[22]} {receive_top_inst/stop_fine_data[1]_3[23]} {receive_top_inst/stop_fine_data[1]_3[24]} {receive_top_inst/stop_fine_data[1]_3[25]} {receive_top_inst/stop_fine_data[1]_3[26]} {receive_top_inst/stop_fine_data[1]_3[27]} {receive_top_inst/stop_fine_data[1]_3[28]} {receive_top_inst/stop_fine_data[1]_3[29]} {receive_top_inst/stop_fine_data[1]_3[30]} {receive_top_inst/stop_fine_data[1]_3[31]}]]
connect_debug_port u_ila_0/probe15 [get_nets [list receive_top_inst/valid]]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clock_top_inst/clk_200M]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[0]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[1]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[2]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[3]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[4]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[5]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[6]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[7]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[8]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[9]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[10]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[11]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[12]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[13]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[14]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[15]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[16]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[17]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[18]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[19]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[20]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[21]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[22]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[23]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[24]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[25]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[26]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[27]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[28]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[29]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[30]} {receive_top_inst/genblk3[1].coarse_cnt_inst/clk_cnt_reg[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {receive_top_inst/coarse_cnt_inst0/coarse_time[0]} {receive_top_inst/coarse_cnt_inst0/coarse_time[1]} {receive_top_inst/coarse_cnt_inst0/coarse_time[2]} {receive_top_inst/coarse_cnt_inst0/coarse_time[3]} {receive_top_inst/coarse_cnt_inst0/coarse_time[4]} {receive_top_inst/coarse_cnt_inst0/coarse_time[5]} {receive_top_inst/coarse_cnt_inst0/coarse_time[6]} {receive_top_inst/coarse_cnt_inst0/coarse_time[7]} {receive_top_inst/coarse_cnt_inst0/coarse_time[8]} {receive_top_inst/coarse_cnt_inst0/coarse_time[9]} {receive_top_inst/coarse_cnt_inst0/coarse_time[10]} {receive_top_inst/coarse_cnt_inst0/coarse_time[11]} {receive_top_inst/coarse_cnt_inst0/coarse_time[12]} {receive_top_inst/coarse_cnt_inst0/coarse_time[13]} {receive_top_inst/coarse_cnt_inst0/coarse_time[14]} {receive_top_inst/coarse_cnt_inst0/coarse_time[15]} {receive_top_inst/coarse_cnt_inst0/coarse_time[16]} {receive_top_inst/coarse_cnt_inst0/coarse_time[17]} {receive_top_inst/coarse_cnt_inst0/coarse_time[18]} {receive_top_inst/coarse_cnt_inst0/coarse_time[19]} {receive_top_inst/coarse_cnt_inst0/coarse_time[20]} {receive_top_inst/coarse_cnt_inst0/coarse_time[21]} {receive_top_inst/coarse_cnt_inst0/coarse_time[22]} {receive_top_inst/coarse_cnt_inst0/coarse_time[23]} {receive_top_inst/coarse_cnt_inst0/coarse_time[24]} {receive_top_inst/coarse_cnt_inst0/coarse_time[25]} {receive_top_inst/coarse_cnt_inst0/coarse_time[26]} {receive_top_inst/coarse_cnt_inst0/coarse_time[27]} {receive_top_inst/coarse_cnt_inst0/coarse_time[28]} {receive_top_inst/coarse_cnt_inst0/coarse_time[29]} {receive_top_inst/coarse_cnt_inst0/coarse_time[30]} {receive_top_inst/coarse_cnt_inst0/coarse_time[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[0]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[1]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[2]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[3]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[4]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[5]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[6]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[7]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[8]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[9]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[10]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[11]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[12]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[13]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[14]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[15]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[16]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[17]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[18]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[19]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[20]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[21]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[22]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[23]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[24]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[25]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[26]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[27]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[28]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[29]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[30]} {receive_top_inst/coarse_cnt_inst0/clk_cnt_reg[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[0]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[1]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[2]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[3]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[4]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[5]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[6]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[7]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[8]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[9]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[10]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[11]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[12]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[13]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[14]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[15]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[16]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[17]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[18]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[19]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[20]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[21]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[22]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[23]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[24]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[25]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[26]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[27]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[28]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[29]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[30]} {receive_top_inst/genblk3[1].coarse_cnt_inst/coarse_time[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 2 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {receive_top_inst/stretch_hit[0]} {receive_top_inst/stretch_hit[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 2 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {receive_top_inst/clr[0]} {receive_top_inst/clr[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 2 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {receive_top_inst/latch[0]} {receive_top_inst/latch[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 2 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {receive_top_inst/hit[0]} {receive_top_inst/hit[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list receive_top_inst/coarse_cnt_inst0/clr]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list receive_top_inst/coarse_cnt_inst0/latch]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {receive_top_inst/genblk3[1].coarse_cnt_inst/clr}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {receive_top_inst/genblk3[1].coarse_cnt_inst/latch}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list receive_top_inst/stop_en]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets receive_clk]
